# Generated by Django 4.2.2 on 2023-07-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moftshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип кард холдера',
                'verbose_name_plural': 'Тип кард холдеров',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='moftshop.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='holderType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='moftshop.holdertype'),
        ),
    ]
