# Generated by Django 4.2.2 on 2023-07-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moftshop', '0002_holdertype_alter_product_category_product_holdertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolderType',
            new_name='ProductType',
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('name',), 'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Типы продуктов'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='holderType',
            new_name='productType',
        ),
    ]
