# Generated by Django 4.2.2 on 2023-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moftshop', '0003_rename_holdertype_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='code',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
